// <auto-generated />
namespace DTO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_required : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_required));
        
        string IMigrationMetadata.Id
        {
            get { return "202006271617298_add_required"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
