// <auto-generated />
namespace DTO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class modifylogin2pk : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modifylogin2pk));
        
        string IMigrationMetadata.Id
        {
            get { return "202006051637124_modifylogin2pk"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
